### ISSUE TITLE
Make --source-folder and --resource-folder configurable

### ISSUE THREAD

**Issue by gorpet** [IntershopCommunicationsAG/wsdl-gradle-plugin#10]
Both folders needs to be configurable to be able to use /src/main/java (or something custom) for source folder.
Now they are hard-coded to 'src' and 'resources' -  wsdl-gradle-plugin/src/main/groovy/com/intershop/gradle/wsdl/tasks/axis2/WSDL2Java.groovy lines 232 and 233.

**Comment by m-raab** [comment]
Do not use src/main/java for the result of the code generation. This destroys Gradle's incremental build feature. The source and the target of a task execution must be different. The output directory self is configurable (line 184) and the directory is marked as output directory.
